language: java
jdk: openjdk21
dist: focal
branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^support\/.*$/
    - /^hotfix\/.*$/
services:
  - docker

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V

script:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false ]] && ([[ $TRAVIS_BRANCH == develop ]] || [[ $TRAVIS_BRANCH == master ]] || [[ $TRAVIS_BRANCH == support/* ]] || [[ $TRAVIS_BRANCH == hotfix/* ]]); then
      #
      # Updload to Maven repo
      #
      echo $GPG_SECRET_KEYS | tr " " "\n" | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
      echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
      mvn -e clean deploy --settings .maven.xml -B -V -Prelease;
      # 
      # Upload to docker hub
      #
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      mvn -P docker -pl dev,gui,restapi jib:build
    else
      mvn -e clean install --settings .maven.xml -Dgpg.skip -B -V
    fi

cache:
  directories:
    - $HOME/.m2
