language: java
jdk: openjdk21
dist: jammy
branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^support\/.*$/
    - /^hotfix\/.*$/
services:
  - docker

install:
  - mvn install -DskipTests -Dmaven.javadoc.skip -Dgpg.skip -B -V

script:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false ]] && ([[ $TRAVIS_BRANCH == develop ]] || [[ $TRAVIS_BRANCH == master ]] || [[ $TRAVIS_BRANCH == support/* ]] || [[ $TRAVIS_BRANCH == hotfix/* ]]); then
      #
      # Upload to Maven repo
      #
      echo $GPG_SECRET_KEYS | tr " " "\n" | base64 --decode | $GPG_EXECUTABLE --import --no-tty --batch --yes
      echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --no-tty --batch --yes
      mvn -e clean deploy --settings .maven.xml -B -V -P release;
    else
      mvn -e clean install --settings .maven.xml -Dgpg.skip -B -V
      # 
      # Build docker images locally and run integration tests
      #
      # mvn -P docker -pl restapi,testing jib:dockerBuild
      # docker compose -f ./testing/src/main/docker/docker-compose.yml -p integtest up -d
      # sleep 30
      # mvn test -pl testing -P integtest
    fi

#after_script:
#  - docker compose -f ./testing/src/main/docker/docker-compose.yml -p integtest down

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false ]] && ([[ $TRAVIS_BRANCH == develop ]] || [[ $TRAVIS_BRANCH == master ]] || [[ $TRAVIS_BRANCH == support/* ]] || [[ $TRAVIS_BRANCH == hotfix/* ]]); then
      # 
      # Upload to docker hub
      #
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      mvn -P docker -pl dev,gui,restapi jib:build
    fi

cache:
  directories:
    - $HOME/.m2
