language: java
jdk: oraclejdk8
dist: trusty
branches: 
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^support\/.*$/
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - echo $TRAVIS_BRANCH
install:
  - mvn --settings .maven.xml install -Dgpg.skip -B -V
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && ( "$TRAVIS_BRANCH" == "develop" || "$TRAVIS_BRANCH" == "master" || "$TRAVIS_BRANCH" == "support/*" ) ]]; then mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease; fi
cache:
  directories:
    - $HOME/.m2
