site_name: Cristal-ISE
repo_url: https://github.com/cristal-ise/cristal-ise
edit_uri: edit/cristalise-docs/docs

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

extra_css:
    - css/extra.css

nav:
    - Home: index.md
    - Overview:
        - Introduction: Introduction.md
        - Getting started: Getting-Started.md
    - Features:
        - Cope with Change: Cope-with-Change.md
        - Evolve Code with Data: Evolve-Code-with-Data.md
        - Built-in Provenance: Built-in-Provenance.md
        - Universal Data Catalogue: Universal-Data-Catalogue.md
        - Process Description: Process-Description.md
        - Built-in Security: Built-in-Security.md
        - Immutable BOs: Immutable-BOs.md
    - Technical Documentation:
        - Technical Introduction: Technical-Introduction.md
        - Client API: API.md
        - Developer Guide:
            - Boot sequence: Boot-Sequence-of-Server.md
            - Reset IORs: Reset-IORs.md
            - Command-line arguments: Command-line-Arguments.md
            - Activity execution: Activity-Execution.md
        - DSL: Domain-Specific-Language-(DSL).md
        - JavaDoc: http://javadoc.io/doc/org.cristalise/cristalise-kernel
    - Tutorials:
        - Basic (Create Patient): Basic-Tutorial.md
        - Advanced (Patient Tracking): tutorial-PatientTracking.md
    - Others:
        - Selected papers: Selected-papers.md
        - Maven Deploy Travis: Maven-Deploy-Travis.md
        - Maven Deploy Travis GPG2: Maven-Deploy-Travis-GPG2.md
        - Glossary: Glossary.md
