package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/AccessDeniedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/dev/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, June 11, 2021 7:33:26 PM PHT
*/


/**************************************************************************
    * The given agent is not permitted to perform the requested action
    **************************************************************************/
public final class AccessDeniedException extends org.omg.CORBA.UserException
{

  public AccessDeniedException ()
  {
    super(AccessDeniedExceptionHelper.id());
  } // ctor


  public AccessDeniedException (String $reason)
  {
    super(AccessDeniedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccessDeniedException
