package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/AccessRightsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The given agent is not permitted to perform the requested action.
    **************************************************************************/
public final class AccessRightsException extends org.omg.CORBA.UserException
{

  public AccessRightsException ()
  {
    super(AccessRightsExceptionHelper.id());
  } // ctor


  public AccessRightsException (String $reason)
  {
    super(AccessRightsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class AccessRightsException
