package org.cristalise.kernel.common;

/**
* org/cristalise/kernel/common/AccessRightsExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**************************************************************************
    * The given agent is not permitted to perform the requested action.
    **************************************************************************/
public final class AccessRightsExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.common.AccessRightsException value = null;

  public AccessRightsExceptionHolder ()
  {
  }

  public AccessRightsExceptionHolder (org.cristalise.kernel.common.AccessRightsException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.common.AccessRightsExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.common.AccessRightsExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.common.AccessRightsExceptionHelper.type ();
  }

}
