package org.cristalise.kernel.common;

/**
* org/cristalise/kernel/common/CannotManageExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**************************************************************************
    * Thrown when the process isn't privileged enough to make the requested 
    * change, either because it is a client process, or its management objects
    * are incorrect.
    **************************************************************************/
public final class CannotManageExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.common.CannotManageException value = null;

  public CannotManageExceptionHolder ()
  {
  }

  public CannotManageExceptionHolder (org.cristalise.kernel.common.CannotManageException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.common.CannotManageExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.common.CannotManageExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.common.CannotManageExceptionHelper.type ();
  }

}
