package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/CannotManageException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**************************************************************************
    * Thrown when the process isn't privileged enough to make the requested 
    * change, either because it is a client process, or its management objects
    * are incorrect.
    **************************************************************************/
public final class CannotManageException extends org.omg.CORBA.UserException
{

  public CannotManageException ()
  {
    super(CannotManageExceptionHelper.id());
  } // ctor


  public CannotManageException (String $reason)
  {
    super(CannotManageExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class CannotManageException
