package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/GTimeStamp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonTypes.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/

public final class GTimeStamp implements org.omg.CORBA.portable.IDLEntity
{
  public int mYear = (int)0;
  public int mMonth = (int)0;
  public int mDay = (int)0;
  public int mHour = (int)0;
  public int mMinute = (int)0;
  public int mSecond = (int)0;
  public int mNano = (int)0;
  public int mTimeOffset = (int)0;

  public GTimeStamp ()
  {
  } // ctor

  public GTimeStamp (int _mYear, int _mMonth, int _mDay, int _mHour, int _mMinute, int _mSecond, int _mNano, int _mTimeOffset)
  {
    mYear = _mYear;
    mMonth = _mMonth;
    mDay = _mDay;
    mHour = _mHour;
    mMinute = _mMinute;
    mSecond = _mSecond;
    mNano = _mNano;
    mTimeOffset = _mTimeOffset;
  } // ctor

} // class GTimeStamp
