package org.cristalise.kernel.common;

/**
* org/cristalise/kernel/common/InvalidCollectionModificationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The modification to the collection could not be performed, due to rules
    * within the collection itself.
    **************************************************************************/
public final class InvalidCollectionModificationHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.common.InvalidCollectionModification value = null;

  public InvalidCollectionModificationHolder ()
  {
  }

  public InvalidCollectionModificationHolder (org.cristalise.kernel.common.InvalidCollectionModification initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.common.InvalidCollectionModificationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.common.InvalidCollectionModificationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.common.InvalidCollectionModificationHelper.type ();
  }

}
