package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/InvalidTransitionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The requested transition is not currently available, or does not exist.
    * Most commonly occurs when the Activity is in a different state than the
    * caller has assumed.
    **************************************************************************/
public final class InvalidTransitionException extends org.omg.CORBA.UserException
{

  public InvalidTransitionException ()
  {
    super(InvalidTransitionExceptionHelper.id());
  } // ctor


  public InvalidTransitionException (String $reason)
  {
    super(InvalidTransitionExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidTransitionException
