package org.cristalise.kernel.common;

/**
* org/cristalise/kernel/common/InvalidTransitionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**************************************************************************
    * The requested transition is not currently available, or does not exist.
    * Most commonly occurs when the Activity is in a different state than the
    * caller has assumed.
    **************************************************************************/
public final class InvalidTransitionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.common.InvalidTransitionException value = null;

  public InvalidTransitionExceptionHolder ()
  {
  }

  public InvalidTransitionExceptionHolder (org.cristalise.kernel.common.InvalidTransitionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.common.InvalidTransitionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.common.InvalidTransitionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.common.InvalidTransitionExceptionHelper.type ();
  }

}
