package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The requested object was not found
    **************************************************************************/
public final class ObjectNotFoundException extends org.omg.CORBA.UserException
{

  public ObjectNotFoundException ()
  {
    super(ObjectNotFoundExceptionHelper.id());
  } // ctor


  public ObjectNotFoundException (String $reason)
  {
    super(ObjectNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectNotFoundException
