package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectCannotBeUpdated.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**************************************************************************
    * The object cannot be changed.
    **************************************************************************/
public final class ObjectCannotBeUpdated extends org.omg.CORBA.UserException
{

  public ObjectCannotBeUpdated ()
  {
    super(ObjectCannotBeUpdatedHelper.id());
  } // ctor


  public ObjectCannotBeUpdated (String $reason)
  {
    super(ObjectCannotBeUpdatedHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectCannotBeUpdated
