package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectCannotBeUpdated.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The object cannot be changed.
    **************************************************************************/
public final class ObjectCannotBeUpdated extends org.omg.CORBA.UserException
{

  public ObjectCannotBeUpdated ()
  {
    super(ObjectCannotBeUpdatedHelper.id());
  } // ctor


  public ObjectCannotBeUpdated (String $reason)
  {
    super(ObjectCannotBeUpdatedHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectCannotBeUpdated
