package org.cristalise.kernel.common;

/**
* org/cristalise/kernel/common/ObjectCannotBeUpdatedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The object cannot be changed.
    **************************************************************************/
public final class ObjectCannotBeUpdatedHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.common.ObjectCannotBeUpdated value = null;

  public ObjectCannotBeUpdatedHolder ()
  {
  }

  public ObjectCannotBeUpdatedHolder (org.cristalise.kernel.common.ObjectCannotBeUpdated initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.common.ObjectCannotBeUpdatedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.common.ObjectCannotBeUpdatedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.common.ObjectCannotBeUpdatedHelper.type ();
  }

}
