package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**************************************************************************
    * The object already exists.
    **************************************************************************/
public final class ObjectAlreadyExistsException extends org.omg.CORBA.UserException
{

  public ObjectAlreadyExistsException ()
  {
    super(ObjectAlreadyExistsExceptionHelper.id());
  } // ctor


  public ObjectAlreadyExistsException (String $reason)
  {
    super(ObjectAlreadyExistsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectAlreadyExistsException
