package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * The object already exists.
    **************************************************************************/
public final class ObjectAlreadyExistsException extends org.omg.CORBA.UserException
{

  public ObjectAlreadyExistsException ()
  {
    super(ObjectAlreadyExistsExceptionHelper.id());
  } // ctor


  public ObjectAlreadyExistsException (String $reason)
  {
    super(ObjectAlreadyExistsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectAlreadyExistsException
