package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectAlreadyExistsException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Saturday, March 14, 2020 10:40:42 AM CET
*/


/**************************************************************************
    * The object already exists.
    **************************************************************************/
public final class ObjectAlreadyExistsException extends org.omg.CORBA.UserException
{

  public ObjectAlreadyExistsException ()
  {
    super(ObjectAlreadyExistsExceptionHelper.id());
  } // ctor


  public ObjectAlreadyExistsException (String $reason)
  {
    super(ObjectAlreadyExistsExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectAlreadyExistsException
