package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/ObjectNotFoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Saturday, March 14, 2020 10:40:42 AM CET
*/


/**************************************************************************
    * The requested object was not found
    **************************************************************************/
public final class ObjectNotFoundException extends org.omg.CORBA.UserException
{

  public ObjectNotFoundException ()
  {
    super(ObjectNotFoundExceptionHelper.id());
  } // ctor


  public ObjectNotFoundException (String $reason)
  {
    super(ObjectNotFoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ObjectNotFoundException
