package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/PersistencyException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonExceptions.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * Error during storing/retrieving objects
    **************************************************************************/
public final class PersistencyException extends org.omg.CORBA.UserException
{

  public PersistencyException ()
  {
    super(PersistencyExceptionHelper.id());
  } // ctor


  public PersistencyException (String $reason)
  {
    super(PersistencyExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class PersistencyException
