package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/SystemKeyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/CommonTypes.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/

abstract public class SystemKeyHelper
{
  private static String  _id = "IDL:org.cristalise.kernel/common/SystemKey:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cristalise.kernel.common.SystemKey that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cristalise.kernel.common.SystemKey extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "msb",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulonglong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "lsb",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.cristalise.kernel.common.SystemKeyHelper.id (), "SystemKey", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cristalise.kernel.common.SystemKey read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cristalise.kernel.common.SystemKey value = new org.cristalise.kernel.common.SystemKey ();
    value.msb = istream.read_ulonglong ();
    value.lsb = istream.read_ulonglong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cristalise.kernel.common.SystemKey value)
  {
    ostream.write_ulonglong (value.msb);
    ostream.write_ulonglong (value.lsb);
  }

}
