package org.cristalise.kernel.common;


/**
* org/cristalise/kernel/common/SystemKey.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/CommonTypes.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/

public final class SystemKey implements org.omg.CORBA.portable.IDLEntity
{
  public long msb = (long)0;
  public long lsb = (long)0;

  public SystemKey ()
  {
  } // ctor

  public SystemKey (long _msb, long _lsb)
  {
    msb = _msb;
    lsb = _lsb;
  } // ctor

} // class SystemKey
