package org.cristalise.kernel.entity;

/**
* org/cristalise/kernel/entity/AgentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/Entity.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * Agent is a ManageableEntity that represents an Activity executor in the 
    * system. It holds a job list, which are persistent requests for execution 
    * from waiting activities assigned to a role that has such Job pushing enabled.
    **************************************************************************/
public final class AgentHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.entity.Agent value = null;

  public AgentHolder ()
  {
  }

  public AgentHolder (org.cristalise.kernel.entity.Agent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.entity.AgentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.entity.AgentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.entity.AgentHelper.type ();
  }

}
