package org.cristalise.kernel.entity;


/**
* org/cristalise/kernel/entity/Agent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/Entity.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**************************************************************************
    * Agent is a ManageableEntity that represents an Activity executor in the 
    * system. It holds a job list, which are persistent requests for execution 
    * from waiting activities assigned to a role that has such Job pushing enabled.
    **************************************************************************/
public interface Agent extends AgentOperations, org.cristalise.kernel.entity.Item, org.omg.CORBA.portable.IDLEntity 
{
} // interface Agent
