package org.cristalise.kernel.entity;

/**
* org/cristalise/kernel/entity/ItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/cristal-ise/workspace/cristal-ise/idl/src/main/idl/Entity.idl
* Wednesday, 11 December 2019 17:43:31 o'clock CET
*/


/**
    * ManageableEntity is the CORBA super-interface for Entities. It is uniquely 
    * identifiable by its <i>system key</i>, and contains XML fragments arranged 
    * in a tree structure. 
    **/
public final class ItemHolder implements org.omg.CORBA.portable.Streamable
{
  public org.cristalise.kernel.entity.Item value = null;

  public ItemHolder ()
  {
  }

  public ItemHolder (org.cristalise.kernel.entity.Item initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.cristalise.kernel.entity.ItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.cristalise.kernel.entity.ItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.cristalise.kernel.entity.ItemHelper.type ();
  }

}
