package org.cristalise.kernel.entity;


/**
* org/cristalise/kernel/entity/ItemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/vagrant/workspace/cristal-ise/idl/src/main/idl/Entity.idl
* Friday, April 10, 2020 7:30:08 PM CEST
*/


/**
    * ManageableEntity is the CORBA super-interface for Entities. It is uniquely 
    * identifiable by its <i>system key</i>, and contains XML fragments arranged 
    * in a tree structure. 
    **/
abstract public class ItemHelper
{
  private static String  _id = "IDL:org.cristalise.kernel/entity/Item:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cristalise.kernel.entity.Item that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cristalise.kernel.entity.Item extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.cristalise.kernel.entity.ItemHelper.id (), "Item");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cristalise.kernel.entity.Item read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ItemStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cristalise.kernel.entity.Item value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.cristalise.kernel.entity.Item narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.cristalise.kernel.entity.Item)
      return (org.cristalise.kernel.entity.Item)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.cristalise.kernel.entity._ItemStub stub = new org.cristalise.kernel.entity._ItemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.cristalise.kernel.entity.Item unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.cristalise.kernel.entity.Item)
      return (org.cristalise.kernel.entity.Item)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.cristalise.kernel.entity._ItemStub stub = new org.cristalise.kernel.entity._ItemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
