/**
 * CRISTAL-iSE Item Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagedPathData } from './pagedPathData';
import { PathData } from './pathData';
import { ItemAliases } from './itemAliases';


/**
 * @type DomainPathGet200Response
 * @export
 */
export type DomainPathGet200Response = Array<ItemAliases> | PagedPathData;

