/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventDataOutcome } from './eventDataOutcome';
import { EventDataTransition } from './eventDataTransition';
import { EventDataActivity } from './eventDataActivity';


export interface EventData { 
    id: number;
    timestamp: string;
    agent: string;
    role: string;
    hasAttachment: boolean;
    outcome?: EventDataOutcome;
    activity: EventDataActivity;
    transition: EventDataTransition;
}

