/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventDataTransitionOneOf { 
    name: string;
    origin: string;
    target: string;
    stateMachine: string;
    stateMachineVersion: number;
}

