/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventDataTransitionOneOf } from './eventDataTransitionOneOf';


/**
 * @type EventDataTransition
 * @export
 */
export type EventDataTransition = EventDataTransitionOneOf | string;

