/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobDataOutcome } from './jobDataOutcome';
import { JobDataActivity } from './jobDataActivity';
import { JobDataItem } from './jobDataItem';
import { JobDataTransition } from './jobDataTransition';
import { JobData } from './jobData';


/**
 * @type ItemUuidJobGet200Response
 * @export
 */
export type ItemUuidJobGet200Response = Array<JobData> | JobData;

