/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDataOutcome { 
    required: boolean;
    schema: string;
    schemaVersion: number;
    schemaUrl: string;
    formTemplateUrl: string;
}

