/**
 * CRISTAL-iSE Item Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDataTransition { 
    name: string;
    id: number;
    origin: string;
    target: string;
    stateMachine: string;
    stateMachineVersion: string;
    stateMachineUrl: string;
}

