/**
 * CRISTAL-iSE Item Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobDataOutcome } from './jobDataOutcome';
import { JobDataActivity } from './jobDataActivity';
import { JobDataItem } from './jobDataItem';
import { JobDataTransition } from './jobDataTransition';


export interface JobData { 
    agent?: string;
    roleOverride?: string;
    item: JobDataItem;
    activity: JobDataActivity;
    transition: JobDataTransition;
    outcome?: JobDataOutcome;
    attachmentMimeTypes?: string;
}

