/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PathData } from './pathData';


export interface PagedPathData { 
    start: number;
    pageSize: number;
    totalRows: number;
    prevPage?: string;
    nextPage?: string;
    rows: Array<PathData>;
}

