/**
 * CRISTAL-iSE Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoleSummary { 
    name: string;
    hasJobList: boolean;
    subroles?: { [key: string]: string; };
    agents?: { [key: string]: string; };
}

