/**
 * CRISTAL-iSE Item Rest API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ViewpointSummaryViewsInner { 
    name: string;
    url: string;
}

