site_name: Cristal-ISE
repo_url: https://github.com/cristal-ise/cristal-ise
edit_uri: edit/cristalise-docs/docs
nav:
    - Home: index.md
    - Getting started: Getting-Started.md 
    - Key features:
        - Cope with Change: Cope-with-Change.md
        - Evolve Code with Data: Evolve-Code-with-Data.md
        - Built-in Provenance: Built-in-Provenance.md
        - Universal Data Catalogue: Universal-Data-Catalogue.md
        - Process Description: Process-Description.md
        - Built-in Security: Built-in-Security.md
        - Immutable BOs: Immutable-BOs.md
    - Documentation:
        - Introduction: Introduction.md
        - Technical Introduction: Technical-Introduction.md
        - Client API: API.md
        - Developer Guide: Developer-Guide.md
        - DSL: Domain-Specific-Language-(DSL).md
        - JavaDoc: http://javadoc.io/doc/org.cristalise/cristalise-kernel
    - Tutorials:
        - Basic ( Create Patient ): Basic-Tutorial.md
        - Adv ( Patient Tracking ): tutorial-PatientTracking.md
    - Selected papers: Selected-papers.md
    - Maven Deploy Travis: Maven-Deploy-Travis.md
    - Maven Deploy Travis GPG2: Maven-Deploy-Travis-GPG2.md

theme: readthedocs
